swiftmailer:
    #url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: smtp
    username: 45db702c5dd0d1
    password: 42e4a6c6dd3dfe
    host: smtp.mailtrap.io
    port: 2525
    auth_mode: cram-md5
